"""Regenerate the JS manifests from the filesystem.

Why: keeps `assets/js/docs-manifest.js` and `assets/js/posts-manifest.js`
in sync with what's actually on disk under `docs/` and `posts/`. Removes
the "I added a doc but forgot the manifest" failure mode.

Usage:
    uv run python scripts/build_manifests.py

The pytest test_doc_links.py asserts the on-disk manifest matches what
this script would produce, so CI will catch drift if a contributor edits
docs but skips the regeneration step.

Conventions:
- docs/ entries are discovered by walking docs/ recursively. Sections are
  picked from each doc's `section:` front-matter; absent that, the leading
  sub-folder name (e.g. evidence/) is used; for root-level docs the
  DEFAULT_SECTION map applies; anything else lands in 'Other'.
- posts/ entries are sorted by `date:` from front-matter (descending).
- Slugs for docs preserve sub-paths (`evidence/round-trip`); for posts
  the slug is just the file stem.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"
POSTS_DIR = REPO_ROOT / "posts"
DOCS_MANIFEST = REPO_ROOT / "assets" / "js" / "docs-manifest.js"
POSTS_MANIFEST = REPO_ROOT / "assets" / "js" / "posts-manifest.js"

# Section ordering. Sections themselves are populated by walking docs/.
DOCS_SECTION_ORDER: list[str] = [
    "Getting Started",
    "Concepts",
    "Architecture",
    "Setup & Operations",
    "Governance",
    "Evidence",
    "Other",
]

# Default section per slug (file stem) used when a doc has no `section:`
# front-matter. Drop a doc into docs/ AND want it sectioned a particular
# way? Either add `section: <name>` to its front-matter (preferred) or
# extend this map.
DEFAULT_SECTION: dict[str, str] = {
    "quickstart": "Getting Started",
    "troubleshooting": "Getting Started",
    "learning-guide": "Concepts",
    "project-scope": "Concepts",
    "design": "Architecture",
    "code-walkthrough": "Architecture",
    "setup-walkthrough": "Setup & Operations",
    "testing": "Setup & Operations",
    "blueprint-policy": "Governance",
}


def _read_front_matter(md: Path) -> dict[str, str]:
    text = md.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end].strip()
    out: dict[str, str] = {}
    for line in block.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _title_for(md: Path) -> str:
    fm = _read_front_matter(md)
    if "title" in fm:
        return fm["title"]
    text = md.read_text(encoding="utf-8")
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return md.stem.replace("-", " ").title()


def _section_for(md: Path, slug: str) -> str:
    """Pick the sidebar section for a doc.

    Order:
      1. `section:` value in the markdown front-matter (authoritative)
      2. Sub-folder name capitalized (e.g. docs/evidence/X.md -> 'Evidence')
      3. DEFAULT_SECTION mapping for known root-level slugs
      4. 'Other' as the catch-all so new docs are never silently dropped
    """
    fm = _read_front_matter(md)
    if "section" in fm and fm["section"]:
        return fm["section"]
    parts = slug.split("/")
    if len(parts) > 1:
        return parts[0].replace("-", " ").title()
    return DEFAULT_SECTION.get(slug, "Other")


def _build_docs_manifest() -> str:
    grouped: dict[str, list[dict]] = {name: [] for name in DOCS_SECTION_ORDER}
    for md in sorted(DOCS_DIR.rglob("*.md")):
        rel = md.relative_to(DOCS_DIR).with_suffix("")
        slug = str(rel).replace("\\", "/")
        section = _section_for(md, slug)
        grouped.setdefault(section, []).append(
            {
                "slug": slug,
                "title": _title_for(md),
                "path": f"docs/{md.relative_to(DOCS_DIR).as_posix()}",
            }
        )

    # Emit known sections in order, then any extras (e.g. user-defined section
    # names from front-matter) alphabetically so output is deterministic.
    sections: list[dict] = []
    seen: set[str] = set()
    for name in DOCS_SECTION_ORDER:
        items = grouped.get(name, [])
        if items:
            sections.append({"section": name, "items": items})
        seen.add(name)
    for name in sorted(grouped):
        if name in seen:
            continue
        items = grouped[name]
        if items:
            sections.append({"section": name, "items": items})

    body = json.dumps(sections, indent=2, ensure_ascii=False)
    return (
        "/**\n"
        " * Sidebar manifest for the docs viewer.\n"
        " * AUTOGENERATED by scripts/build_manifests.py — do not edit by hand.\n"
        " * To add a doc: drop a .md file under docs/ and re-run the script.\n"
        " * Override the auto-assigned section by adding `section: <name>` to\n"
        " * the doc's YAML front-matter; otherwise the leading folder name (or\n"
        " * the DEFAULT_SECTION mapping) is used.\n"
        " * The pytest suite (test_doc_links.py) fails CI if this drifts from disk.\n"
        " */\n"
        f"window.DOCS_MANIFEST = {body};\n"
    )


def _build_posts_manifest() -> str:
    posts = []
    for md in POSTS_DIR.glob("*.md"):
        fm = _read_front_matter(md)
        posts.append(
            {
                "slug": md.stem,
                "title": fm.get("title", _title_for(md)),
                "date": fm.get("date", "2026-01-01"),
                "path": f"posts/{md.name}",
            }
        )
    posts.sort(key=lambda p: p["date"])
    body = json.dumps(posts, indent=2, ensure_ascii=False)
    return (
        "/**\n"
        " * Learning Series posts manifest.\n"
        " * AUTOGENERATED by scripts/build_manifests.py — do not edit by hand.\n"
        " */\n"
        f"window.POSTS_MANIFEST = {body};\n"
    )


def main() -> None:
    DOCS_MANIFEST.write_text(_build_docs_manifest(), encoding="utf-8")
    POSTS_MANIFEST.write_text(_build_posts_manifest(), encoding="utf-8")
    print(f"Wrote {DOCS_MANIFEST.relative_to(REPO_ROOT)}")
    print(f"Wrote {POSTS_MANIFEST.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
