"""Regenerate the JS manifests from the filesystem.

Why: keeps `assets/js/docs-manifest.js` and `assets/js/posts-manifest.js`
in sync with what's actually on disk under `docs/` and `posts/`. Removes
the "I added a doc but forgot the manifest" failure mode.

Usage:
    uv run python scripts/build_manifests.py

The pytest test_doc_links.py asserts the on-disk manifest matches what
this script would produce, so CI will catch drift if a contributor edits
docs but skips the regeneration step.

Conventions:
- docs/ entries are grouped by section using the leading folder name OR
  a `section:` value in the markdown front-matter. Files at the docs/
  root are placed in sections by an explicit mapping below.
- posts/ entries are sorted by `date:` from front-matter (descending).
- Slugs for docs preserve sub-paths (`evidence/round-trip`); for posts
  the slug is just the file stem.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"
POSTS_DIR = REPO_ROOT / "posts"
DOCS_MANIFEST = REPO_ROOT / "assets" / "js" / "docs-manifest.js"
POSTS_MANIFEST = REPO_ROOT / "assets" / "js" / "posts-manifest.js"

# Explicit section assignment for files at docs/ root, plus ordering.
DOCS_SECTIONS: list[tuple[str, list[str]]] = [
    ("Getting Started", ["quickstart", "troubleshooting"]),
    ("Concepts", ["learning-guide", "project-scope"]),
    ("Architecture", ["design", "code-walkthrough"]),
    ("Setup & Operations", ["setup-walkthrough", "testing"]),
    ("Governance", ["blueprint-policy"]),
    ("Evidence", []),  # populated from docs/evidence/*.md
]


def _read_front_matter(md: Path) -> dict[str, str]:
    text = md.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end].strip()
    out: dict[str, str] = {}
    for line in block.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _title_for(md: Path) -> str:
    fm = _read_front_matter(md)
    if "title" in fm:
        return fm["title"]
    text = md.read_text(encoding="utf-8")
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return md.stem.replace("-", " ").title()


def _build_docs_manifest() -> str:
    sections: list[dict] = []
    for section_name, slugs in DOCS_SECTIONS:
        items = []
        if section_name == "Evidence":
            evidence_dir = DOCS_DIR / "evidence"
            if evidence_dir.exists():
                for md in sorted(evidence_dir.glob("*.md")):
                    slug = f"evidence/{md.stem}"
                    items.append(
                        {
                            "slug": slug,
                            "title": _title_for(md),
                            "path": f"docs/evidence/{md.name}",
                        }
                    )
        else:
            for slug in slugs:
                md = DOCS_DIR / f"{slug}.md"
                if md.exists():
                    items.append(
                        {
                            "slug": slug,
                            "title": _title_for(md),
                            "path": f"docs/{md.name}",
                        }
                    )
        if items:
            sections.append({"section": section_name, "items": items})

    body = json.dumps(sections, indent=2, ensure_ascii=False)
    return (
        "/**\n"
        " * Sidebar manifest for the docs viewer.\n"
        " * AUTOGENERATED by scripts/build_manifests.py — do not edit by hand.\n"
        " * To add a doc: drop a .md file under docs/ and re-run the script.\n"
        " * The pytest suite (test_doc_links.py) fails CI if this drifts from disk.\n"
        " */\n"
        f"window.DOCS_MANIFEST = {body};\n"
    )


def _build_posts_manifest() -> str:
    posts = []
    for md in POSTS_DIR.glob("*.md"):
        fm = _read_front_matter(md)
        posts.append(
            {
                "slug": md.stem,
                "title": fm.get("title", _title_for(md)),
                "date": fm.get("date", "2026-01-01"),
                "path": f"posts/{md.name}",
            }
        )
    posts.sort(key=lambda p: p["date"])
    body = json.dumps(posts, indent=2, ensure_ascii=False)
    return (
        "/**\n"
        " * Learning Series posts manifest.\n"
        " * AUTOGENERATED by scripts/build_manifests.py — do not edit by hand.\n"
        " */\n"
        f"window.POSTS_MANIFEST = {body};\n"
    )


def main() -> None:
    DOCS_MANIFEST.write_text(_build_docs_manifest(), encoding="utf-8")
    POSTS_MANIFEST.write_text(_build_posts_manifest(), encoding="utf-8")
    print(f"Wrote {DOCS_MANIFEST.relative_to(REPO_ROOT)}")
    print(f"Wrote {POSTS_MANIFEST.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
